spring:
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework: INFO
    com.mycompany.mimecasttest.textsearch: DEBUG


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    parser:
      STRICT_DUPLICATE_DETECTION: true

myapp:
  documentation:
    title: Text Search API
    description: '@project.description@'
    version: '@project.version@'

  servers: localhost, swathi1
  proxy-url: localhost
  frontend: /swagger-ui.html
